name: CI-testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  ci:
    name: ci-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: build
        run: go build -v ./...

      - name: get-gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run Tests
        run: gotestsum --format testname --jsonfile ./test-output.log -- --timeout 5m ./...

      - name: upload-logs
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: ./test-output.log
          retention-days: 30

      - name: run
        run: go run main.go ./...